[package]
name = "app"
version = "0.0.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true }
server = { path = "../server" }

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
